branches:
    only:
        - master
install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update -y
    - sudo apt-get install texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra latexmk texlive-science -y

cache: apt

# sudo: false
# addons:
#   apt:
#     # sources: texlive-backports/ppa 
#     packages:
#       - texlive-latex-extra
#       - texlive-xetex
#       - latexmk
#       - texlive-science
#       - texlive-latex-recommended

script: 
    - latexmk
