branches:
    only:
        - master
install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update -y
    - sudo apt-get install texlive-latex-extra latexmk texlive-science texlive-luatex -y
cache: apt

# addons:
#   apt:
#     # sources: texlive-backports/ppa 
#     packages:
#       - texlive-latex-extra
#       - texlive-luatex
#       - texlive-fonts-extra
#       - texlive-bibtex-extra
#       - latexmk
#       - texlive-science

script: 
    - latexmk
